// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEnabledAdmins = `-- name: CountEnabledAdmins :one
SELECT COUNT(*) FROM users WHERE role = 'admin' AND enabled = true
`

func (q *Queries) CountEnabledAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEnabledAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, name, token_hash, role, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, token_hash, role, last_used_at, expires_at, created_at
`

type CreateAPITokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	TokenHash string             `json:"token_hash"`
	Role      string             `json:"role"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Role,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Role,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_log (action, entity_type, entity_id, changes, actor_user_id, actor_type, actor_api_token_id, request_id, ip_address, object_type, object_id, before_state, after_state)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9::inet, $10, $11, $12, $13)
RETURNING id, action, entity_type, entity_id, changes, actor_user_id, actor_type, actor_api_token_id, request_id, ip_address, object_type, object_id, before_state, after_state, created_at
`

type CreateAuditLogParams struct {
	Action          string      `json:"action"`
	EntityType      string      `json:"entity_type"`
	EntityID        pgtype.UUID `json:"entity_id"`
	Changes         []byte      `json:"changes"`
	ActorUserID     pgtype.UUID `json:"actor_user_id"`
	ActorType       pgtype.Text `json:"actor_type"`
	ActorApiTokenID pgtype.UUID `json:"actor_api_token_id"`
	RequestID       pgtype.Text `json:"request_id"`
	IpAddress       netip.Addr  `json:"ip_address"`
	ObjectType      pgtype.Text `json:"object_type"`
	ObjectID        pgtype.UUID `json:"object_id"`
	BeforeState     []byte      `json:"before_state"`
	AfterState      []byte      `json:"after_state"`
}

type CreateAuditLogRow struct {
	ID              pgtype.UUID        `json:"id"`
	Action          string             `json:"action"`
	EntityType      string             `json:"entity_type"`
	EntityID        pgtype.UUID        `json:"entity_id"`
	Changes         []byte             `json:"changes"`
	ActorUserID     pgtype.UUID        `json:"actor_user_id"`
	ActorType       pgtype.Text        `json:"actor_type"`
	ActorApiTokenID pgtype.UUID        `json:"actor_api_token_id"`
	RequestID       pgtype.Text        `json:"request_id"`
	IpAddress       *netip.Addr        `json:"ip_address"`
	ObjectType      pgtype.Text        `json:"object_type"`
	ObjectID        pgtype.UUID        `json:"object_id"`
	BeforeState     []byte             `json:"before_state"`
	AfterState      []byte             `json:"after_state"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (CreateAuditLogRow, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Changes,
		arg.ActorUserID,
		arg.ActorType,
		arg.ActorApiTokenID,
		arg.RequestID,
		arg.IpAddress,
		arg.ObjectType,
		arg.ObjectID,
		arg.BeforeState,
		arg.AfterState,
	)
	var i CreateAuditLogRow
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Changes,
		&i.ActorUserID,
		&i.ActorType,
		&i.ActorApiTokenID,
		&i.RequestID,
		&i.IpAddress,
		&i.ObjectType,
		&i.ObjectID,
		&i.BeforeState,
		&i.AfterState,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, session_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, session_hash, expires_at, created_at, last_seen_at
`

type CreateSessionParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	SessionHash string             `json:"session_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.SessionHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, password_hash, role, enabled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, display_name, password_hash, role, enabled, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	DisplayName  string `json:"display_name"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
	Enabled      bool   `json:"enabled"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Role,
		arg.Enabled,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Enabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens WHERE id = $1
`

func (q *Queries) DeleteAPIToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAPIToken, id)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, user_id, name, token_hash, role, last_used_at, expires_at, created_at
FROM api_tokens WHERE token_hash = $1 LIMIT 1
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Role,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPITokenByID = `-- name: GetAPITokenByID :one
SELECT id, user_id, name, token_hash, role, last_used_at, expires_at, created_at
FROM api_tokens WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAPITokenByID(ctx context.Context, id pgtype.UUID) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByID, id)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Role,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByHash = `-- name: GetSessionByHash :one
SELECT id, user_id, session_hash, expires_at, created_at, last_seen_at
FROM sessions WHERE session_hash = $1 LIMIT 1
`

func (q *Queries) GetSessionByHash(ctx context.Context, sessionHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByHash, sessionHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, password_hash, role, enabled, last_login_at, created_at, updated_at
FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Enabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, password_hash, role, enabled, last_login_at, created_at, updated_at
FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Enabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, user_id, name, token_hash, role, last_used_at, expires_at, created_at
FROM api_tokens ORDER BY created_at DESC
`

func (q *Queries) ListAPITokens(ctx context.Context) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listAPITokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiToken
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Role,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, action, entity_type, entity_id, changes, actor_user_id, actor_type, actor_api_token_id, request_id, ip_address, object_type, object_id, before_state, after_state, created_at
FROM audit_log
WHERE
    ($1::uuid IS NULL OR actor_user_id = $1)
    AND ($2::text IS NULL OR action = $2)
    AND ($3::text IS NULL OR object_type = $3)
    AND ($4::uuid IS NULL OR object_id = $4)
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListAuditLogsParams struct {
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	Action      pgtype.Text `json:"action"`
	ObjectType  pgtype.Text `json:"object_type"`
	ObjectID    pgtype.UUID `json:"object_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListAuditLogsRow struct {
	ID              pgtype.UUID        `json:"id"`
	Action          string             `json:"action"`
	EntityType      string             `json:"entity_type"`
	EntityID        pgtype.UUID        `json:"entity_id"`
	Changes         []byte             `json:"changes"`
	ActorUserID     pgtype.UUID        `json:"actor_user_id"`
	ActorType       pgtype.Text        `json:"actor_type"`
	ActorApiTokenID pgtype.UUID        `json:"actor_api_token_id"`
	RequestID       pgtype.Text        `json:"request_id"`
	IpAddress       *netip.Addr        `json:"ip_address"`
	ObjectType      pgtype.Text        `json:"object_type"`
	ObjectID        pgtype.UUID        `json:"object_id"`
	BeforeState     []byte             `json:"before_state"`
	AfterState      []byte             `json:"after_state"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.ActorUserID,
		arg.Action,
		arg.ObjectType,
		arg.ObjectID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsRow
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Changes,
			&i.ActorUserID,
			&i.ActorType,
			&i.ActorApiTokenID,
			&i.RequestID,
			&i.IpAddress,
			&i.ObjectType,
			&i.ObjectID,
			&i.BeforeState,
			&i.AfterState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, display_name, password_hash, role, enabled, last_login_at, created_at, updated_at
FROM users ORDER BY created_at ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Role,
			&i.Enabled,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) TouchAPIToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIToken, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET display_name = $2, role = $3, enabled = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, email, display_name, password_hash, role, enabled, last_login_at, created_at, updated_at
`

type UpdateUserParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
	Role        string      `json:"role"`
	Enabled     bool        `json:"enabled"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.DisplayName,
		arg.Role,
		arg.Enabled,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Enabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users SET last_login_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, email, display_name, password_hash, role, enabled, last_login_at, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Enabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
