// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discovery.sql

package db

import (
	"context"
	"net"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDiscoveryResult = `-- name: CreateDiscoveryResult :one
INSERT INTO discovery_results (
    scan_id, prefix_id, address, mac_address, hostname, reverse_dns,
    open_ports, latency_ms, classification, raw
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, scan_id, prefix_id, address, mac_address, hostname, reverse_dns, open_ports, latency_ms, classification, seen_at, raw, ignored, accepted_at, created_ip_address_id, created_at, updated_at
`

type CreateDiscoveryResultParams struct {
	ScanID         pgtype.UUID      `json:"scan_id"`
	PrefixID       pgtype.UUID      `json:"prefix_id"`
	Address        netip.Addr       `json:"address"`
	MacAddress     net.HardwareAddr `json:"mac_address"`
	Hostname       pgtype.Text      `json:"hostname"`
	ReverseDns     pgtype.Text      `json:"reverse_dns"`
	OpenPorts      []byte           `json:"open_ports"`
	LatencyMs      pgtype.Int4      `json:"latency_ms"`
	Classification string           `json:"classification"`
	Raw            []byte           `json:"raw"`
}

func (q *Queries) CreateDiscoveryResult(ctx context.Context, arg CreateDiscoveryResultParams) (DiscoveryResult, error) {
	row := q.db.QueryRow(ctx, createDiscoveryResult,
		arg.ScanID,
		arg.PrefixID,
		arg.Address,
		arg.MacAddress,
		arg.Hostname,
		arg.ReverseDns,
		arg.OpenPorts,
		arg.LatencyMs,
		arg.Classification,
		arg.Raw,
	)
	var i DiscoveryResult
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.PrefixID,
		&i.Address,
		&i.MacAddress,
		&i.Hostname,
		&i.ReverseDns,
		&i.OpenPorts,
		&i.LatencyMs,
		&i.Classification,
		&i.SeenAt,
		&i.Raw,
		&i.Ignored,
		&i.AcceptedAt,
		&i.CreatedIpAddressID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDiscoveryScan = `-- name: CreateDiscoveryScan :one
INSERT INTO discovery_scans (prefix_id, status)
VALUES ($1, $2)
RETURNING id, prefix_id, status, started_at, completed_at, error, created_at, updated_at
`

type CreateDiscoveryScanParams struct {
	PrefixID pgtype.UUID `json:"prefix_id"`
	Status   string      `json:"status"`
}

func (q *Queries) CreateDiscoveryScan(ctx context.Context, arg CreateDiscoveryScanParams) (DiscoveryScan, error) {
	row := q.db.QueryRow(ctx, createDiscoveryScan, arg.PrefixID, arg.Status)
	var i DiscoveryScan
	err := row.Scan(
		&i.ID,
		&i.PrefixID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDiscoveryResult = `-- name: GetDiscoveryResult :one
SELECT id, scan_id, prefix_id, address, mac_address, hostname, reverse_dns, open_ports, latency_ms, classification, seen_at, raw, ignored, accepted_at, created_ip_address_id, created_at, updated_at FROM discovery_results WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDiscoveryResult(ctx context.Context, id pgtype.UUID) (DiscoveryResult, error) {
	row := q.db.QueryRow(ctx, getDiscoveryResult, id)
	var i DiscoveryResult
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.PrefixID,
		&i.Address,
		&i.MacAddress,
		&i.Hostname,
		&i.ReverseDns,
		&i.OpenPorts,
		&i.LatencyMs,
		&i.Classification,
		&i.SeenAt,
		&i.Raw,
		&i.Ignored,
		&i.AcceptedAt,
		&i.CreatedIpAddressID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDiscoveryScan = `-- name: GetDiscoveryScan :one
SELECT id, prefix_id, status, started_at, completed_at, error, created_at, updated_at FROM discovery_scans WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDiscoveryScan(ctx context.Context, id pgtype.UUID) (DiscoveryScan, error) {
	row := q.db.QueryRow(ctx, getDiscoveryScan, id)
	var i DiscoveryScan
	err := row.Scan(
		&i.ID,
		&i.PrefixID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrefixesForScheduledScans = `-- name: GetPrefixesForScheduledScans :many
SELECT p.id, p.site_id, p.vlan_id, p.prefix, p.description, p.created_at, p.updated_at, p.scan_enabled, p.scan_interval_seconds FROM prefixes p
WHERE p.scan_enabled = true
AND NOT EXISTS (
    SELECT 1 FROM discovery_scans ds
    WHERE ds.prefix_id = p.id
    AND ds.status IN ('queued', 'running')
)
AND (
    NOT EXISTS (
        SELECT 1 FROM discovery_scans ds
        WHERE ds.prefix_id = p.id
        AND ds.status = 'completed'
    )
    OR EXISTS (
        SELECT 1 FROM discovery_scans ds
        WHERE ds.prefix_id = p.id
        AND ds.status = 'completed'
        AND ds.completed_at < CURRENT_TIMESTAMP - (p.scan_interval_seconds * interval '1 second')
    )
)
`

func (q *Queries) GetPrefixesForScheduledScans(ctx context.Context) ([]Prefix, error) {
	rows, err := q.db.Query(ctx, getPrefixesForScheduledScans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prefix
	for rows.Next() {
		var i Prefix
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.VlanID,
			&i.Prefix,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScanEnabled,
			&i.ScanIntervalSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentDiscoveryResultsByAddress = `-- name: GetRecentDiscoveryResultsByAddress :many
SELECT id, scan_id, prefix_id, address, mac_address, hostname, reverse_dns, open_ports, latency_ms, classification, seen_at, raw, ignored, accepted_at, created_ip_address_id, created_at, updated_at FROM discovery_results
WHERE prefix_id = $1 AND address = $2
ORDER BY seen_at DESC
LIMIT 5
`

type GetRecentDiscoveryResultsByAddressParams struct {
	PrefixID pgtype.UUID `json:"prefix_id"`
	Address  netip.Addr  `json:"address"`
}

func (q *Queries) GetRecentDiscoveryResultsByAddress(ctx context.Context, arg GetRecentDiscoveryResultsByAddressParams) ([]DiscoveryResult, error) {
	rows, err := q.db.Query(ctx, getRecentDiscoveryResultsByAddress, arg.PrefixID, arg.Address)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveryResult
	for rows.Next() {
		var i DiscoveryResult
		if err := rows.Scan(
			&i.ID,
			&i.ScanID,
			&i.PrefixID,
			&i.Address,
			&i.MacAddress,
			&i.Hostname,
			&i.ReverseDns,
			&i.OpenPorts,
			&i.LatencyMs,
			&i.Classification,
			&i.SeenAt,
			&i.Raw,
			&i.Ignored,
			&i.AcceptedAt,
			&i.CreatedIpAddressID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRunningOrQueuedScansForPrefix = `-- name: GetRunningOrQueuedScansForPrefix :many
SELECT id, prefix_id, status, started_at, completed_at, error, created_at, updated_at FROM discovery_scans
WHERE prefix_id = $1 AND status IN ('queued', 'running')
`

func (q *Queries) GetRunningOrQueuedScansForPrefix(ctx context.Context, prefixID pgtype.UUID) ([]DiscoveryScan, error) {
	rows, err := q.db.Query(ctx, getRunningOrQueuedScansForPrefix, prefixID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveryScan
	for rows.Next() {
		var i DiscoveryScan
		if err := rows.Scan(
			&i.ID,
			&i.PrefixID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoveryResults = `-- name: ListDiscoveryResults :many
SELECT id, scan_id, prefix_id, address, mac_address, hostname, reverse_dns, open_ports, latency_ms, classification, seen_at, raw, ignored, accepted_at, created_ip_address_id, created_at, updated_at FROM discovery_results
WHERE ($1::uuid IS NULL OR scan_id = $1)
AND ($2::uuid IS NULL OR prefix_id = $2)
AND ($3::text IS NULL OR classification = $3)
AND ($4::boolean IS NULL OR ignored = $4)
ORDER BY seen_at DESC
LIMIT $6 OFFSET $5
`

type ListDiscoveryResultsParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
	Column3 string      `json:"column_3"`
	Column4 bool        `json:"column_4"`
	Offset  int32       `json:"offset"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) ListDiscoveryResults(ctx context.Context, arg ListDiscoveryResultsParams) ([]DiscoveryResult, error) {
	rows, err := q.db.Query(ctx, listDiscoveryResults,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveryResult
	for rows.Next() {
		var i DiscoveryResult
		if err := rows.Scan(
			&i.ID,
			&i.ScanID,
			&i.PrefixID,
			&i.Address,
			&i.MacAddress,
			&i.Hostname,
			&i.ReverseDns,
			&i.OpenPorts,
			&i.LatencyMs,
			&i.Classification,
			&i.SeenAt,
			&i.Raw,
			&i.Ignored,
			&i.AcceptedAt,
			&i.CreatedIpAddressID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoveryScans = `-- name: ListDiscoveryScans :many
SELECT id, prefix_id, status, started_at, completed_at, error, created_at, updated_at FROM discovery_scans
WHERE ($1::uuid IS NULL OR prefix_id = $1)
AND ($2::text IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListDiscoveryScansParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 string      `json:"column_2"`
	Offset  int32       `json:"offset"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) ListDiscoveryScans(ctx context.Context, arg ListDiscoveryScansParams) ([]DiscoveryScan, error) {
	rows, err := q.db.Query(ctx, listDiscoveryScans,
		arg.Column1,
		arg.Column2,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveryScan
	for rows.Next() {
		var i DiscoveryScan
		if err := rows.Scan(
			&i.ID,
			&i.PrefixID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDiscoveryResultAccepted = `-- name: UpdateDiscoveryResultAccepted :one
UPDATE discovery_results
SET accepted_at = CURRENT_TIMESTAMP,
    created_ip_address_id = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, scan_id, prefix_id, address, mac_address, hostname, reverse_dns, open_ports, latency_ms, classification, seen_at, raw, ignored, accepted_at, created_ip_address_id, created_at, updated_at
`

type UpdateDiscoveryResultAcceptedParams struct {
	ID                 pgtype.UUID `json:"id"`
	CreatedIpAddressID pgtype.UUID `json:"created_ip_address_id"`
}

func (q *Queries) UpdateDiscoveryResultAccepted(ctx context.Context, arg UpdateDiscoveryResultAcceptedParams) (DiscoveryResult, error) {
	row := q.db.QueryRow(ctx, updateDiscoveryResultAccepted, arg.ID, arg.CreatedIpAddressID)
	var i DiscoveryResult
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.PrefixID,
		&i.Address,
		&i.MacAddress,
		&i.Hostname,
		&i.ReverseDns,
		&i.OpenPorts,
		&i.LatencyMs,
		&i.Classification,
		&i.SeenAt,
		&i.Raw,
		&i.Ignored,
		&i.AcceptedAt,
		&i.CreatedIpAddressID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDiscoveryResultIgnored = `-- name: UpdateDiscoveryResultIgnored :one
UPDATE discovery_results
SET ignored = true,
    classification = 'ignored',
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, scan_id, prefix_id, address, mac_address, hostname, reverse_dns, open_ports, latency_ms, classification, seen_at, raw, ignored, accepted_at, created_ip_address_id, created_at, updated_at
`

func (q *Queries) UpdateDiscoveryResultIgnored(ctx context.Context, id pgtype.UUID) (DiscoveryResult, error) {
	row := q.db.QueryRow(ctx, updateDiscoveryResultIgnored, id)
	var i DiscoveryResult
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.PrefixID,
		&i.Address,
		&i.MacAddress,
		&i.Hostname,
		&i.ReverseDns,
		&i.OpenPorts,
		&i.LatencyMs,
		&i.Classification,
		&i.SeenAt,
		&i.Raw,
		&i.Ignored,
		&i.AcceptedAt,
		&i.CreatedIpAddressID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDiscoveryScanStatus = `-- name: UpdateDiscoveryScanStatus :one
UPDATE discovery_scans
SET status = $2,
    started_at = COALESCE($3, started_at),
    completed_at = COALESCE($4, completed_at),
    error = COALESCE($5, error),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, prefix_id, status, started_at, completed_at, error, created_at, updated_at
`

type UpdateDiscoveryScanStatusParams struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Error       pgtype.Text        `json:"error"`
}

func (q *Queries) UpdateDiscoveryScanStatus(ctx context.Context, arg UpdateDiscoveryScanStatusParams) (DiscoveryScan, error) {
	row := q.db.QueryRow(ctx, updateDiscoveryScanStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.Error,
	)
	var i DiscoveryScan
	err := row.Scan(
		&i.ID,
		&i.PrefixID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
