// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Name       string             `json:"name"`
	TokenHash  string             `json:"token_hash"`
	Role       string             `json:"role"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID              pgtype.UUID        `json:"id"`
	Action          string             `json:"action"`
	EntityType      string             `json:"entity_type"`
	EntityID        pgtype.UUID        `json:"entity_id"`
	Changes         []byte             `json:"changes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ActorUserID     pgtype.UUID        `json:"actor_user_id"`
	ActorType       pgtype.Text        `json:"actor_type"`
	ActorApiTokenID pgtype.UUID        `json:"actor_api_token_id"`
	RequestID       pgtype.Text        `json:"request_id"`
	IpAddress       *netip.Addr        `json:"ip_address"`
	ObjectType      pgtype.Text        `json:"object_type"`
	ObjectID        pgtype.UUID        `json:"object_id"`
	BeforeState     []byte             `json:"before_state"`
	AfterState      []byte             `json:"after_state"`
}

type Device struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	SiteID      pgtype.UUID        `json:"site_id"`
	Description pgtype.Text        `json:"description"`
	Status      pgtype.Text        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type DiscoveryResult struct {
	ID                 pgtype.UUID        `json:"id"`
	ScanID             pgtype.UUID        `json:"scan_id"`
	PrefixID           pgtype.UUID        `json:"prefix_id"`
	Address            netip.Addr         `json:"address"`
	MacAddress         net.HardwareAddr   `json:"mac_address"`
	Hostname           pgtype.Text        `json:"hostname"`
	ReverseDns         pgtype.Text        `json:"reverse_dns"`
	OpenPorts          []byte             `json:"open_ports"`
	LatencyMs          pgtype.Int4        `json:"latency_ms"`
	Classification     string             `json:"classification"`
	SeenAt             pgtype.Timestamptz `json:"seen_at"`
	Raw                []byte             `json:"raw"`
	Ignored            bool               `json:"ignored"`
	AcceptedAt         pgtype.Timestamptz `json:"accepted_at"`
	CreatedIpAddressID pgtype.UUID        `json:"created_ip_address_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type DiscoveryScan struct {
	ID          pgtype.UUID        `json:"id"`
	PrefixID    pgtype.UUID        `json:"prefix_id"`
	Status      string             `json:"status"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Error       pgtype.Text        `json:"error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Incident struct {
	ID             pgtype.UUID        `json:"id"`
	MonitorID      pgtype.UUID        `json:"monitor_id"`
	Status         string             `json:"status"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	Severity       string             `json:"severity"`
	AcknowledgedAt pgtype.Timestamptz `json:"acknowledged_at"`
	Summary        string             `json:"summary"`
	Details        pgtype.Text        `json:"details"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Interface struct {
	ID         pgtype.UUID        `json:"id"`
	DeviceID   pgtype.UUID        `json:"device_id"`
	Name       string             `json:"name"`
	MacAddress pgtype.Text        `json:"mac_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type IpAddress struct {
	ID          pgtype.UUID        `json:"id"`
	PrefixID    pgtype.UUID        `json:"prefix_id"`
	IpAddress   string             `json:"ip_address"`
	InterfaceID pgtype.UUID        `json:"interface_id"`
	Status      pgtype.Text        `json:"status"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
}

type Monitor struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Slug string      `json:"slug"`
	// http, tcp, ping, dns, tls, push, postgres
	MonitorType        string             `json:"monitor_type"`
	Target             string             `json:"target"`
	Config             []byte             `json:"config"`
	IpAddressID        pgtype.UUID        `json:"ip_address_id"`
	DeviceID           pgtype.UUID        `json:"device_id"`
	IntervalSeconds    int32              `json:"interval_seconds"`
	TimeoutSeconds     int32              `json:"timeout_seconds"`
	RetryCount         int32              `json:"retry_count"`
	Enabled            bool               `json:"enabled"`
	Status             string             `json:"status"`
	LastCheckedAt      pgtype.Timestamptz `json:"last_checked_at"`
	LastStatusChangeAt pgtype.Timestamptz `json:"last_status_change_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	PushTokenHash      pgtype.Text        `json:"push_token_hash"`
	LastHeartbeatAt    pgtype.Timestamptz `json:"last_heartbeat_at"`
}

type MonitorResult struct {
	ID           pgtype.UUID        `json:"id"`
	MonitorID    pgtype.UUID        `json:"monitor_id"`
	Status       string             `json:"status"`
	LatencyMs    pgtype.Int4        `json:"latency_ms"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CheckedAt    pgtype.Timestamptz `json:"checked_at"`
	Details      []byte             `json:"details"`
}

type NotificationChannel struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	ChannelType string             `json:"channel_type"`
	Enabled     bool               `json:"enabled"`
	Config      []byte             `json:"config"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type NotificationDelivery struct {
	ID        pgtype.UUID        `json:"id"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	EventType string             `json:"event_type"`
	Status    string             `json:"status"`
	Attempts  int32              `json:"attempts"`
	LastError pgtype.Text        `json:"last_error"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	SentAt    pgtype.Timestamptz `json:"sent_at"`
}

type Prefix struct {
	ID                  pgtype.UUID        `json:"id"`
	SiteID              pgtype.UUID        `json:"site_id"`
	VlanID              pgtype.UUID        `json:"vlan_id"`
	Prefix              string             `json:"prefix"`
	Description         pgtype.Text        `json:"description"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ScanEnabled         bool               `json:"scan_enabled"`
	ScanIntervalSeconds int32              `json:"scan_interval_seconds"`
}

type Session struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	SessionHash string             `json:"session_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
}

type Site struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type StatusPage struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	Slug          string             `json:"slug"`
	Description   pgtype.Text        `json:"description"`
	Public        bool               `json:"public"`
	ShowUptime    bool               `json:"show_uptime"`
	ShowIncidents bool               `json:"show_incidents"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type StatusPageMonitor struct {
	StatusPageID pgtype.UUID        `json:"status_page_id"`
	MonitorID    pgtype.UUID        `json:"monitor_id"`
	DisplayName  pgtype.Text        `json:"display_name"`
	DisplayOrder int32              `json:"display_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	PasswordHash string             `json:"-"`
	Role         string             `json:"role"`
	Enabled      bool               `json:"enabled"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Vlan struct {
	ID          pgtype.UUID        `json:"id"`
	SiteID      pgtype.UUID        `json:"site_id"`
	VlanID      int32              `json:"vlan_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
