// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// Manual additions for Phase 6 auth entities follow the generated code.

package db

import (
	"net"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

// AuditLog is the legacy struct kept for backward compatibility.
type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Changes    []byte             `json:"changes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// AuditLogEntry is the Phase 6 extended audit log model with actor metadata.
type AuditLogEntry struct {
	ID              pgtype.UUID        `json:"id"`
	Action          string             `json:"action"`
	EntityType      string             `json:"entity_type"`
	EntityID        pgtype.UUID        `json:"entity_id"`
	Changes         []byte             `json:"changes"`
	ActorUserID     pgtype.UUID        `json:"actor_user_id"`
	ActorType       pgtype.Text        `json:"actor_type"`
	ActorAPITokenID pgtype.UUID        `json:"actor_api_token_id"`
	RequestID       pgtype.Text        `json:"request_id"`
	IPAddress       *netip.Addr        `json:"ip_address"`
	ObjectType      pgtype.Text        `json:"object_type"`
	ObjectID        pgtype.UUID        `json:"object_id"`
	BeforeState     []byte             `json:"before_state"`
	AfterState      []byte             `json:"after_state"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

// User represents a Blackgrid application user.
type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	PasswordHash string             `json:"-"` // never serialized
	Role         string             `json:"role"`
	Enabled      bool               `json:"enabled"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Session represents an authenticated browser session.
type Session struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	SessionHash string             `json:"-"` // never serialized
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
}

// ApiToken represents a long-lived API token for automation.
type ApiToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Name       string             `json:"name"`
	TokenHash  string             `json:"-"` // never serialized
	Role       string             `json:"role"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Device struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	SiteID      pgtype.UUID        `json:"site_id"`
	Description pgtype.Text        `json:"description"`
	Status      pgtype.Text        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type DiscoveryResult struct {
	ID                 pgtype.UUID        `json:"id"`
	ScanID             pgtype.UUID        `json:"scan_id"`
	PrefixID           pgtype.UUID        `json:"prefix_id"`
	Address            netip.Addr         `json:"address"`
	MacAddress         net.HardwareAddr   `json:"mac_address"`
	Hostname           pgtype.Text        `json:"hostname"`
	ReverseDns         pgtype.Text        `json:"reverse_dns"`
	OpenPorts          []byte             `json:"open_ports"`
	LatencyMs          pgtype.Int4        `json:"latency_ms"`
	Classification     string             `json:"classification"`
	SeenAt             pgtype.Timestamptz `json:"seen_at"`
	Raw                []byte             `json:"raw"`
	Ignored            bool               `json:"ignored"`
	AcceptedAt         pgtype.Timestamptz `json:"accepted_at"`
	CreatedIpAddressID pgtype.UUID        `json:"created_ip_address_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type DiscoveryScan struct {
	ID          pgtype.UUID        `json:"id"`
	PrefixID    pgtype.UUID        `json:"prefix_id"`
	Status      string             `json:"status"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Error       pgtype.Text        `json:"error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Incident struct {
	ID             pgtype.UUID        `json:"id"`
	MonitorID      pgtype.UUID        `json:"monitor_id"`
	Status         string             `json:"status"`
	Severity       string             `json:"severity"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	AcknowledgedAt pgtype.Timestamptz `json:"acknowledged_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	Summary        string             `json:"summary"`
	Details        pgtype.Text        `json:"details"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type NotificationChannel struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	ChannelType string             `json:"channel_type"`
	Enabled     bool               `json:"enabled"`
	Config      []byte             `json:"config"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type NotificationDelivery struct {
	ID        pgtype.UUID        `json:"id"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	EventType string             `json:"event_type"`
	Status    string             `json:"status"`
	Attempts  int32              `json:"attempts"`
	LastError pgtype.Text        `json:"last_error"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	SentAt    pgtype.Timestamptz `json:"sent_at"`
}

type Interface struct {
	ID         pgtype.UUID        `json:"id"`
	DeviceID   pgtype.UUID        `json:"device_id"`
	Name       string             `json:"name"`
	MacAddress pgtype.Text        `json:"mac_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type IpAddress struct {
	ID          pgtype.UUID        `json:"id"`
	PrefixID    pgtype.UUID        `json:"prefix_id"`
	IpAddress   string             `json:"ip_address"`
	InterfaceID pgtype.UUID        `json:"interface_id"`
	Status      pgtype.Text        `json:"status"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
}

type Monitor struct {
	ID                 pgtype.UUID
	Name               string
	Slug               string
	MonitorType        string
	Target             string
	Config             []byte
	IpAddressID        pgtype.UUID
	DeviceID           pgtype.UUID
	IntervalSeconds    int32
	TimeoutSeconds     int32
	RetryCount         int32
	Enabled            bool
	Status             string
	LastCheckedAt      pgtype.Timestamptz
	LastStatusChangeAt pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type MonitorResult struct {
	ID           pgtype.UUID        `json:"id"`
	MonitorID    pgtype.UUID        `json:"monitor_id"`
	Status       string             `json:"status"`
	LatencyMs    pgtype.Int4        `json:"latency_ms"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CheckedAt    pgtype.Timestamptz `json:"checked_at"`
}

type Prefix struct {
	ID                  pgtype.UUID        `json:"id"`
	SiteID              pgtype.UUID        `json:"site_id"`
	VlanID              pgtype.UUID        `json:"vlan_id"`
	Prefix              string             `json:"prefix"`
	Description         pgtype.Text        `json:"description"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ScanEnabled         bool               `json:"scan_enabled"`
	ScanIntervalSeconds int32              `json:"scan_interval_seconds"`
}

type Site struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Vlan struct {
	ID          pgtype.UUID        `json:"id"`
	SiteID      pgtype.UUID        `json:"site_id"`
	VlanID      int32              `json:"vlan_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
