// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         pgtype.UUID
	Action     string
	EntityType string
	EntityID   pgtype.UUID
	Changes    []byte
	CreatedAt  pgtype.Timestamptz
}

type Device struct {
	ID          pgtype.UUID
	Name        string
	SiteID      pgtype.UUID
	Description pgtype.Text
	Status      pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type DiscoveryResult struct {
	ID           pgtype.UUID
	ScanID       pgtype.UUID
	IpAddress    string
	MacAddress   pgtype.Text
	Hostname     pgtype.Text
	IsActive     pgtype.Bool
	DiscoveredAt pgtype.Timestamptz
}

type DiscoveryScan struct {
	ID         pgtype.UUID
	PrefixID   pgtype.UUID
	Status     string
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}

type Incident struct {
	ID          pgtype.UUID
	MonitorID   pgtype.UUID
	Status      string
	StartedAt   pgtype.Timestamptz
	ResolvedAt  pgtype.Timestamptz
	Description pgtype.Text
}

type Interface struct {
	ID         pgtype.UUID
	DeviceID   pgtype.UUID
	Name       string
	MacAddress pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type IpAddress struct {
	ID          pgtype.UUID
	PrefixID    pgtype.UUID
	IpAddress   string
	InterfaceID pgtype.UUID
	Status      pgtype.Text
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Monitor struct {
	ID              pgtype.UUID
	Name            string
	Type            string
	Target          string
	IntervalSeconds pgtype.Int4
	Status          pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type MonitorResult struct {
	ID           pgtype.UUID
	MonitorID    pgtype.UUID
	Status       string
	LatencyMs    pgtype.Int4
	ErrorMessage pgtype.Text
	CheckedAt    pgtype.Timestamptz
}

type Prefix struct {
	ID          pgtype.UUID
	SiteID      pgtype.UUID
	VlanID      pgtype.UUID
	Prefix      string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Site struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Vlan struct {
	ID          pgtype.UUID
	SiteID      pgtype.UUID
	VlanID      int32
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
