// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (name, site_id, description, status) VALUES ($1, $2, $3, $4) RETURNING id, name, site_id, description, status, created_at, updated_at
`

type CreateDeviceParams struct {
	Name        string
	SiteID      pgtype.UUID
	Description pgtype.Text
	Status      pgtype.Text
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.Name,
		arg.SiteID,
		arg.Description,
		arg.Status,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SiteID,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIPAddress = `-- name: CreateIPAddress :one
INSERT INTO ip_addresses (prefix_id, ip_address, interface_id, status, description) VALUES ($1, $2, $3, $4, $5) RETURNING id, prefix_id, ip_address, interface_id, status, description, created_at, updated_at
`

type CreateIPAddressParams struct {
	PrefixID    pgtype.UUID
	IpAddress   string
	InterfaceID pgtype.UUID
	Status      pgtype.Text
	Description pgtype.Text
}

func (q *Queries) CreateIPAddress(ctx context.Context, arg CreateIPAddressParams) (IpAddress, error) {
	row := q.db.QueryRow(ctx, createIPAddress,
		arg.PrefixID,
		arg.IpAddress,
		arg.InterfaceID,
		arg.Status,
		arg.Description,
	)
	var i IpAddress
	err := row.Scan(
		&i.ID,
		&i.PrefixID,
		&i.IpAddress,
		&i.InterfaceID,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO monitors (name, slug, monitor_type, target, config, ip_address_id, device_id, interval_seconds, timeout_seconds, retry_count, enabled, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) RETURNING id, name, slug, monitor_type, target, config, ip_address_id, device_id, interval_seconds, timeout_seconds, retry_count, enabled, status, last_checked_at, last_status_change_at, created_at, updated_at
`

type CreateMonitorParams struct {
	Name            string
	Slug            string
	MonitorType     string
	Target          string
	Config          []byte
	IpAddressID     pgtype.UUID
	DeviceID        pgtype.UUID
	IntervalSeconds int32
	TimeoutSeconds  int32
	RetryCount      int32
	Enabled         bool
	Status          string
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, createMonitor,
		arg.Name,
		arg.Slug,
		arg.MonitorType,
		arg.Target,
		arg.Config,
		arg.IpAddressID,
		arg.DeviceID,
		arg.IntervalSeconds,
		arg.TimeoutSeconds,
		arg.RetryCount,
		arg.Enabled,
		arg.Status,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.MonitorType,
		&i.Target,
		&i.Config,
		&i.IpAddressID,
		&i.DeviceID,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.RetryCount,
		&i.Enabled,
		&i.Status,
		&i.LastCheckedAt,
		&i.LastStatusChangeAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMonitorResult = `-- name: CreateMonitorResult :one
INSERT INTO monitor_results (monitor_id, status, latency_ms, error_message)
VALUES ($1, $2, $3, $4) RETURNING id, monitor_id, status, latency_ms, error_message, checked_at
`

type CreateMonitorResultParams struct {
	MonitorID    pgtype.UUID
	Status       string
	LatencyMs    pgtype.Int4
	ErrorMessage pgtype.Text
}

func (q *Queries) CreateMonitorResult(ctx context.Context, arg CreateMonitorResultParams) (MonitorResult, error) {
	row := q.db.QueryRow(ctx, createMonitorResult,
		arg.MonitorID,
		arg.Status,
		arg.LatencyMs,
		arg.ErrorMessage,
	)
	var i MonitorResult
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.Status,
		&i.LatencyMs,
		&i.ErrorMessage,
		&i.CheckedAt,
	)
	return i, err
}

const createPrefix = `-- name: CreatePrefix :one
INSERT INTO prefixes (site_id, vlan_id, prefix, description) VALUES ($1, $2, $3, $4) RETURNING id, site_id, vlan_id, prefix, description, created_at, updated_at
`

type CreatePrefixParams struct {
	SiteID      pgtype.UUID
	VlanID      pgtype.UUID
	Prefix      string
	Description pgtype.Text
}

func (q *Queries) CreatePrefix(ctx context.Context, arg CreatePrefixParams) (Prefix, error) {
	row := q.db.QueryRow(ctx, createPrefix,
		arg.SiteID,
		arg.VlanID,
		arg.Prefix,
		arg.Description,
	)
	var i Prefix
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.VlanID,
		&i.Prefix,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSite = `-- name: CreateSite :one
INSERT INTO sites (name, description) VALUES ($1, $2) RETURNING id, name, description, created_at, updated_at
`

type CreateSiteParams struct {
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSite, arg.Name, arg.Description)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVlan = `-- name: CreateVlan :one
INSERT INTO vlans (site_id, vlan_id, name, description) VALUES ($1, $2, $3, $4) RETURNING id, site_id, vlan_id, name, description, created_at, updated_at
`

type CreateVlanParams struct {
	SiteID      pgtype.UUID
	VlanID      int32
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateVlan(ctx context.Context, arg CreateVlanParams) (Vlan, error) {
	row := q.db.QueryRow(ctx, createVlan,
		arg.SiteID,
		arg.VlanID,
		arg.Name,
		arg.Description,
	)
	var i Vlan
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.VlanID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = $1
`

func (q *Queries) DeleteDevice(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDevice, id)
	return err
}

const deleteIPAddress = `-- name: DeleteIPAddress :exec
DELETE FROM ip_addresses WHERE id = $1
`

func (q *Queries) DeleteIPAddress(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteIPAddress, id)
	return err
}

const deleteMonitor = `-- name: DeleteMonitor :exec
DELETE FROM monitors WHERE id = $1
`

func (q *Queries) DeleteMonitor(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMonitor, id)
	return err
}

const deletePrefix = `-- name: DeletePrefix :exec
DELETE FROM prefixes WHERE id = $1
`

func (q *Queries) DeletePrefix(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePrefix, id)
	return err
}

const deleteSite = `-- name: DeleteSite :exec
DELETE FROM sites WHERE id = $1
`

func (q *Queries) DeleteSite(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSite, id)
	return err
}

const deleteVlan = `-- name: DeleteVlan :exec
DELETE FROM vlans WHERE id = $1
`

func (q *Queries) DeleteVlan(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVlan, id)
	return err
}

const getDevice = `-- name: GetDevice :one
SELECT id, name, site_id, description, status, created_at, updated_at FROM devices WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDevice(ctx context.Context, id pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SiteID,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDevices = `-- name: GetDevices :many
SELECT id, name, site_id, description, status, created_at, updated_at FROM devices ORDER BY name
`

func (q *Queries) GetDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.Query(ctx, getDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SiteID,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIPAddress = `-- name: GetIPAddress :one
SELECT id, prefix_id, ip_address, interface_id, status, description, created_at, updated_at FROM ip_addresses WHERE id = $1 LIMIT 1
`

func (q *Queries) GetIPAddress(ctx context.Context, id pgtype.UUID) (IpAddress, error) {
	row := q.db.QueryRow(ctx, getIPAddress, id)
	var i IpAddress
	err := row.Scan(
		&i.ID,
		&i.PrefixID,
		&i.IpAddress,
		&i.InterfaceID,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIPAddresses = `-- name: GetIPAddresses :many
SELECT id, prefix_id, ip_address, interface_id, status, description, created_at, updated_at FROM ip_addresses ORDER BY ip_address
`

func (q *Queries) GetIPAddresses(ctx context.Context) ([]IpAddress, error) {
	rows, err := q.db.Query(ctx, getIPAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IpAddress
	for rows.Next() {
		var i IpAddress
		if err := rows.Scan(
			&i.ID,
			&i.PrefixID,
			&i.IpAddress,
			&i.InterfaceID,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIPAddressesByPrefix = `-- name: GetIPAddressesByPrefix :many
SELECT id, prefix_id, ip_address, interface_id, status, description, created_at, updated_at FROM ip_addresses WHERE prefix_id = $1 ORDER BY ip_address
`

func (q *Queries) GetIPAddressesByPrefix(ctx context.Context, prefixID pgtype.UUID) ([]IpAddress, error) {
	rows, err := q.db.Query(ctx, getIPAddressesByPrefix, prefixID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IpAddress
	for rows.Next() {
		var i IpAddress
		if err := rows.Scan(
			&i.ID,
			&i.PrefixID,
			&i.IpAddress,
			&i.InterfaceID,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonitor = `-- name: GetMonitor :one
SELECT id, name, slug, monitor_type, target, config, ip_address_id, device_id, interval_seconds, timeout_seconds, retry_count, enabled, status, last_checked_at, last_status_change_at, created_at, updated_at FROM monitors WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMonitor(ctx context.Context, id pgtype.UUID) (Monitor, error) {
	row := q.db.QueryRow(ctx, getMonitor, id)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.MonitorType,
		&i.Target,
		&i.Config,
		&i.IpAddressID,
		&i.DeviceID,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.RetryCount,
		&i.Enabled,
		&i.Status,
		&i.LastCheckedAt,
		&i.LastStatusChangeAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMonitorResults = `-- name: GetMonitorResults :many
SELECT id, monitor_id, status, latency_ms, error_message, checked_at FROM monitor_results WHERE monitor_id = $1 ORDER BY checked_at DESC LIMIT $2 OFFSET $3
`

type GetMonitorResultsParams struct {
	MonitorID pgtype.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) GetMonitorResults(ctx context.Context, arg GetMonitorResultsParams) ([]MonitorResult, error) {
	rows, err := q.db.Query(ctx, getMonitorResults, arg.MonitorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonitorResult
	for rows.Next() {
		var i MonitorResult
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.Status,
			&i.LatencyMs,
			&i.ErrorMessage,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonitors = `-- name: GetMonitors :many
SELECT id, name, slug, monitor_type, target, config, ip_address_id, device_id, interval_seconds, timeout_seconds, retry_count, enabled, status, last_checked_at, last_status_change_at, created_at, updated_at FROM monitors ORDER BY name
`

func (q *Queries) GetMonitors(ctx context.Context) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, getMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.MonitorType,
			&i.Target,
			&i.Config,
			&i.IpAddressID,
			&i.DeviceID,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.RetryCount,
			&i.Enabled,
			&i.Status,
			&i.LastCheckedAt,
			&i.LastStatusChangeAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonitorsDueForCheck = `-- name: GetMonitorsDueForCheck :many
SELECT id, name, slug, monitor_type, target, config, ip_address_id, device_id, interval_seconds, timeout_seconds, retry_count, enabled, status, last_checked_at, last_status_change_at, created_at, updated_at FROM monitors
WHERE enabled = true
  AND status != 'paused'
  AND (last_checked_at IS NULL OR last_checked_at < CURRENT_TIMESTAMP - (interval_seconds || ' seconds')::interval)
ORDER BY last_checked_at ASC NULLS FIRST
`

func (q *Queries) GetMonitorsDueForCheck(ctx context.Context) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, getMonitorsDueForCheck)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.MonitorType,
			&i.Target,
			&i.Config,
			&i.IpAddressID,
			&i.DeviceID,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.RetryCount,
			&i.Enabled,
			&i.Status,
			&i.LastCheckedAt,
			&i.LastStatusChangeAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrefix = `-- name: GetPrefix :one
SELECT id, site_id, vlan_id, prefix, description, created_at, updated_at FROM prefixes WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPrefix(ctx context.Context, id pgtype.UUID) (Prefix, error) {
	row := q.db.QueryRow(ctx, getPrefix, id)
	var i Prefix
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.VlanID,
		&i.Prefix,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrefixes = `-- name: GetPrefixes :many
SELECT id, site_id, vlan_id, prefix, description, created_at, updated_at FROM prefixes ORDER BY prefix
`

func (q *Queries) GetPrefixes(ctx context.Context) ([]Prefix, error) {
	rows, err := q.db.Query(ctx, getPrefixes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prefix
	for rows.Next() {
		var i Prefix
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.VlanID,
			&i.Prefix,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSite = `-- name: GetSite :one
SELECT id, name, description, created_at, updated_at FROM sites WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSite(ctx context.Context, id pgtype.UUID) (Site, error) {
	row := q.db.QueryRow(ctx, getSite, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSites = `-- name: GetSites :many
SELECT id, name, description, created_at, updated_at FROM sites ORDER BY name
`

func (q *Queries) GetSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.Query(ctx, getSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVlan = `-- name: GetVlan :one
SELECT id, site_id, vlan_id, name, description, created_at, updated_at FROM vlans WHERE id = $1 LIMIT 1
`

func (q *Queries) GetVlan(ctx context.Context, id pgtype.UUID) (Vlan, error) {
	row := q.db.QueryRow(ctx, getVlan, id)
	var i Vlan
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.VlanID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVlans = `-- name: GetVlans :many
SELECT id, site_id, vlan_id, name, description, created_at, updated_at FROM vlans ORDER BY vlan_id
`

func (q *Queries) GetVlans(ctx context.Context) ([]Vlan, error) {
	rows, err := q.db.Query(ctx, getVlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vlan
	for rows.Next() {
		var i Vlan
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.VlanID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE devices SET name = $2, site_id = $3, description = $4, status = $5, updated_at = CURRENT_TIMESTAMP WHERE id = $1 RETURNING id, name, site_id, description, status, created_at, updated_at
`

type UpdateDeviceParams struct {
	ID          pgtype.UUID
	Name        string
	SiteID      pgtype.UUID
	Description pgtype.Text
	Status      pgtype.Text
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevice,
		arg.ID,
		arg.Name,
		arg.SiteID,
		arg.Description,
		arg.Status,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SiteID,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIPAddress = `-- name: UpdateIPAddress :one
UPDATE ip_addresses SET prefix_id = $2, ip_address = $3, interface_id = $4, status = $5, description = $6, updated_at = CURRENT_TIMESTAMP WHERE id = $1 RETURNING id, prefix_id, ip_address, interface_id, status, description, created_at, updated_at
`

type UpdateIPAddressParams struct {
	ID          pgtype.UUID
	PrefixID    pgtype.UUID
	IpAddress   string
	InterfaceID pgtype.UUID
	Status      pgtype.Text
	Description pgtype.Text
}

func (q *Queries) UpdateIPAddress(ctx context.Context, arg UpdateIPAddressParams) (IpAddress, error) {
	row := q.db.QueryRow(ctx, updateIPAddress,
		arg.ID,
		arg.PrefixID,
		arg.IpAddress,
		arg.InterfaceID,
		arg.Status,
		arg.Description,
	)
	var i IpAddress
	err := row.Scan(
		&i.ID,
		&i.PrefixID,
		&i.IpAddress,
		&i.InterfaceID,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMonitor = `-- name: UpdateMonitor :one
UPDATE monitors
SET name = $2, slug = $3, monitor_type = $4, target = $5, config = $6, ip_address_id = $7, device_id = $8, interval_seconds = $9, timeout_seconds = $10, retry_count = $11, enabled = $12, status = $13, last_checked_at = $14, last_status_change_at = $15, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 RETURNING id, name, slug, monitor_type, target, config, ip_address_id, device_id, interval_seconds, timeout_seconds, retry_count, enabled, status, last_checked_at, last_status_change_at, created_at, updated_at
`

type UpdateMonitorParams struct {
	ID                 pgtype.UUID
	Name               string
	Slug               string
	MonitorType        string
	Target             string
	Config             []byte
	IpAddressID        pgtype.UUID
	DeviceID           pgtype.UUID
	IntervalSeconds    int32
	TimeoutSeconds     int32
	RetryCount         int32
	Enabled            bool
	Status             string
	LastCheckedAt      pgtype.Timestamptz
	LastStatusChangeAt pgtype.Timestamptz
}

func (q *Queries) UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, updateMonitor,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.MonitorType,
		arg.Target,
		arg.Config,
		arg.IpAddressID,
		arg.DeviceID,
		arg.IntervalSeconds,
		arg.TimeoutSeconds,
		arg.RetryCount,
		arg.Enabled,
		arg.Status,
		arg.LastCheckedAt,
		arg.LastStatusChangeAt,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.MonitorType,
		&i.Target,
		&i.Config,
		&i.IpAddressID,
		&i.DeviceID,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.RetryCount,
		&i.Enabled,
		&i.Status,
		&i.LastCheckedAt,
		&i.LastStatusChangeAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePrefix = `-- name: UpdatePrefix :one
UPDATE prefixes SET site_id = $2, vlan_id = $3, prefix = $4, description = $5, updated_at = CURRENT_TIMESTAMP WHERE id = $1 RETURNING id, site_id, vlan_id, prefix, description, created_at, updated_at
`

type UpdatePrefixParams struct {
	ID          pgtype.UUID
	SiteID      pgtype.UUID
	VlanID      pgtype.UUID
	Prefix      string
	Description pgtype.Text
}

func (q *Queries) UpdatePrefix(ctx context.Context, arg UpdatePrefixParams) (Prefix, error) {
	row := q.db.QueryRow(ctx, updatePrefix,
		arg.ID,
		arg.SiteID,
		arg.VlanID,
		arg.Prefix,
		arg.Description,
	)
	var i Prefix
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.VlanID,
		&i.Prefix,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSite = `-- name: UpdateSite :one
UPDATE sites SET name = $2, description = $3, updated_at = CURRENT_TIMESTAMP WHERE id = $1 RETURNING id, name, description, created_at, updated_at
`

type UpdateSiteParams struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
}

func (q *Queries) UpdateSite(ctx context.Context, arg UpdateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, updateSite, arg.ID, arg.Name, arg.Description)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVlan = `-- name: UpdateVlan :one
UPDATE vlans SET site_id = $2, vlan_id = $3, name = $4, description = $5, updated_at = CURRENT_TIMESTAMP WHERE id = $1 RETURNING id, site_id, vlan_id, name, description, created_at, updated_at
`

type UpdateVlanParams struct {
	ID          pgtype.UUID
	SiteID      pgtype.UUID
	VlanID      int32
	Name        string
	Description pgtype.Text
}

func (q *Queries) UpdateVlan(ctx context.Context, arg UpdateVlanParams) (Vlan, error) {
	row := q.db.QueryRow(ctx, updateVlan,
		arg.ID,
		arg.SiteID,
		arg.VlanID,
		arg.Name,
		arg.Description,
	)
	var i Vlan
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.VlanID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
