// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package db

import (
	"context"
)

const cleanupAuditLogs = `-- name: CleanupAuditLogs :exec
DELETE FROM audit_log
WHERE created_at < CURRENT_TIMESTAMP - ($1::int || ' days')::interval
`

func (q *Queries) CleanupAuditLogs(ctx context.Context, dollar_1 int32) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupAuditLogs, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanupDiscoveryResults = `-- name: CleanupDiscoveryResults :exec
DELETE FROM discovery_results
WHERE seen_at < CURRENT_TIMESTAMP - ($1::int || ' days')::interval
`

func (q *Queries) CleanupDiscoveryResults(ctx context.Context, dollar_1 int32) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupDiscoveryResults, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanupDiscoveryScans = `-- name: CleanupDiscoveryScans :exec
DELETE FROM discovery_scans
WHERE created_at < CURRENT_TIMESTAMP - ($1::int || ' days')::interval
`

func (q *Queries) CleanupDiscoveryScans(ctx context.Context, dollar_1 int32) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupDiscoveryScans, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanupMonitorResults = `-- name: CleanupMonitorResults :exec
DELETE FROM monitor_results
WHERE checked_at < CURRENT_TIMESTAMP - ($1::int || ' days')::interval
`

func (q *Queries) CleanupMonitorResults(ctx context.Context, dollar_1 int32) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupMonitorResults, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanupNotificationDeliveries = `-- name: CleanupNotificationDeliveries :exec
DELETE FROM notification_deliveries
WHERE created_at < CURRENT_TIMESTAMP - ($1::int || ' days')::interval
`

func (q *Queries) CleanupNotificationDeliveries(ctx context.Context, dollar_1 int32) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupNotificationDeliveries, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
